name: Deploy to cPanel via FTP

on:
  push:
    branches: ["main"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_FIREBASE_CREDENTIALS: "${{ secrets.FIREBASE_CONFIG }}"
      NEXT_PUBLIC_MAILROUTE: ${{ secrets.MAILROUTE }}
      NEXT_PUBLIC_TRACKER_TOKEN: ${{ secrets.TRACKER_TOKEN }}
      NEXT_PUBLIC_EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "yarn"

      - name: Install dependencies and build project
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build
          npm run export

      - name: List files in the repository
        run: ls -al

      - name: Copy `default_img` file to `Search`
        run: cp public/default_img.jpg Search/

      - name: Install LFTP (FTP Client)
        run: sudo apt-get install lftp

      - name: Delete all files except `.well-known`
        run: |
          lftp -c "
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }};
          cd public_html;
          find . -mindepth 1 ! -name '.well-known' -exec rm -rf {} +;
          bye;
          "

      - name: Upload exported Next.js site to cPanel
        run: |
          lftp -c "
          open -u ${{ secrets.FTP_USERNAME }},${{ secrets.FTP_PASSWORD }} ${{ secrets.FTP_HOST }};
          mirror -R --delete --verbose out public_html;
          bye;
          "