name: Deploy to cPanel via FTP

on:
  push:
    branches: ["master"]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      NEXT_PUBLIC_FIREBASE_CREDENTIALS: "${{ secrets.FIREBASE_CONFIG }}"
      NEXT_PUBLIC_MAILROUTE: ${{ secrets.MAILROUTE }}
      NEXT_PUBLIC_TRACKER_TOKEN: ${{ secrets.TRACKER_TOKEN }}
      NEXT_PUBLIC_EMAIL_TOKEN: ${{ secrets.EMAIL_TOKEN }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
          cache: "yarn"

      - name: Install dependencies and build project
        run: |
          if [ -e yarn.lock ]; then
            yarn install --frozen-lockfile
          elif [ -e package-lock.json ]; then
            npm ci
          else
            npm i
          fi
          npm run build
          npm run export

      - name: Copy `noImage` file to `Search`
        run: cp default_img.jpg out/Search/

      - name: Install LFTP (FTP Client)
        run: sudo apt-get install lftp